### ISSUE TITLE
[New Feature Request] Automatically submit sitemap to search engine APIs

### ISSUE THREAD

**Issue by Glench** [bartholomej/svelte-sitemap#23]
Please excuse me if this is out of the scope of this project, but it would be really cool if this library, in addition to generating the sitemap, also had an option to ping search engine APIs that the sitemap had been updated (e.g. [Google's Search Console API](https://developers.google.com/webmaster-tools/v1/sitemaps/submit)). Right now I'm doing this manually.

**Comment by bartholomej** [comment]
Hi Glen,
I understand your need. But this library does not aspire to be the ultimate solution for the entire sitemap flow.
It's just a single-purpose small helper ;)

I recommend using [the available examples](https://developers.google.com/webmaster-tools/v1/sitemaps/submit?apix=true#try-it) or ready-made libraries that ping the Google Search Console once the application is deployed.
It's pretty simple ;)

_Maybe I can prepare a small example in the readme of this library, but it will only be an example and the implmentation will be up to you._

**Comment by bartholomej** [comment]
@Glench @crazycto
This is how you can easily do it with Github Action. You should run this step after deploy step.

Create file in your repository: `.github/sitemap.yml`
```yaml
name: Ping Google about updated sitemap

on:
  push:
    branches: [ master ]

jobs:
  ping:
    name: Ping Google
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP GET request
        # Example: `curl http://www.google.com/ping?sitemap=https://www.example.com/sitemap.xml`
        run: curl http://www.google.com/ping?sitemap=FULL_URL_OF_YOUR/sitemap.xml
```

Let me know if this is enough for you.

**Comment by crazycto** [comment]
Hello @bartholomej,

Thanks, this is a nice solution.

Just for the records, [this](https://www.npmjs.com/package/netlify-plugin-submit-sitemap) is a Netlify plugin that does just that.

I guess that for us who are not using Netlify this is the best solution to automate the process.

Couple GH Actions tips:
- [This](https://github.com/marketplace/actions/cloudflare-pages-await) waits for Cloudflare Pages deployment
- [This](https://github.com/marketplace/actions/await-for-vercel-deployment) waits for Vercel deployment

Hope this helps.

**Comment by jasongitmail** [comment]
I extended this to ping Google only if the new sitemap has changed, using a hash of the sitemap stored in Github Actions cache for comparison: 

```yaml
- name: Configure cache
  id: sitemap-cache
  uses: actions/cache@v2
  with:
    path: ~/sitemap-hash.txt
    key: ${{ runner.os }}-sitemap-hash

- name: Check if sitemap.xml has changed
  id: check-sitemap
  run: |
    new_hash=$(sha256sum ./.svelte-kit/output/prerendered/pages/sitemap.xml | awk '{print $1}')
    if [ "${{ steps.sitemap-cache.outputs.cache-hit }}" == 'true' ] && grep -Fxq "${new_hash}" ~/sitemap-hash.txt; then
      echo "::set-output name=changed::false"
    else
      echo "::set-output name=changed::true"
    fi
    echo "${new_hash}" > ~/sitemap-hash.txt

- name: Send HTTP GET request
  run: curl http://www.google.com/ping?sitemap=FULL_URL_OF_YOUR/sitemap.xml
  if: steps.check-sitemap.outputs.changed == 'true'
```
